#!/usr/bin/env python3
"""
wav2header.py — convert WAV files to PROGMEM C headers for the drum machine.

Output format matches the Sample descriptor in resampling_player_spec.md:
mono int16 PCM array + length + source sample rate.

Usage:
    python wav2header.py kick.wav snare.wav hat.wav clap.wav -o kit_default.h

Each input becomes one array named sample_<basename> with companion
constants. A summary table struct is emitted at the end for easy
registration with SampleStore.

Only 16-bit PCM WAV input is supported (8/24/32-bit: convert first).
Stereo is downmixed to mono by averaging. Sample rate is preserved and
recorded in the header — the ResamplingPlayer corrects pitch for rates
other than the audio rate, so 22050 Hz sources are fine and half the size.
"""

import argparse
import os
import re
import struct
import sys
import wave


def sanitize(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if s and s[0].isdigit():
        s = "_" + s
    return s.lower()


def load_wav(path: str):
    with wave.open(path, "rb") as w:
        channels = w.getnchannels()
        width = w.getsampwidth()
        rate = w.getframerate()
        frames = w.getnframes()
        if width != 2:
            sys.exit(f"{path}: only 16-bit PCM WAV supported (got {8*width}-bit)")
        raw = w.readframes(frames)

    samples = struct.unpack(f"<{frames * channels}h", raw)
    if channels == 1:
        mono = list(samples)
    else:
        mono = [
            sum(samples[i:i + channels]) // channels
            for i in range(0, len(samples), channels)
        ]
    return mono, rate


def emit_sample(out, name: str, data, rate: int):
    out.write(f"// {name}: {len(data)} samples @ {rate} Hz "
              f"({len(data) / rate:.3f} s, {len(data) * 2} bytes)\n")
    out.write(f"const int16_t sample_{name}[] PROGMEM = {{\n")
    for i in range(0, len(data), 12):
        row = ", ".join(f"{v:6d}" for v in data[i:i + 12])
        out.write(f"  {row},\n")
    out.write("};\n")
    out.write(f"const uint32_t sample_{name}_len  = {len(data)};\n")
    out.write(f"const uint32_t sample_{name}_rate = {rate};\n\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("wavs", nargs="+", help="input .wav files (16-bit PCM)")
    ap.add_argument("-o", "--output", default="kit_default.h", help="output header")
    args = ap.parse_args()

    names = []
    guard = sanitize(os.path.basename(args.output)).upper()

    with open(args.output, "w", encoding="ascii") as out:
        out.write(f"// Generated by wav2header.py - do not edit by hand.\n")
        out.write(f"// Inputs: {', '.join(os.path.basename(p) for p in args.wavs)}\n")
        out.write(f"#ifndef {guard}\n#define {guard}\n\n")
        out.write("#include <Arduino.h>\n\n")

        for path in args.wavs:
            name = sanitize(os.path.splitext(os.path.basename(path))[0])
            data, rate = load_wav(path)
            emit_sample(out, name, data, rate)
            names.append(name)
            print(f"{path}: {len(data)} samples @ {rate} Hz -> sample_{name}")

        # Registration table: { data, length, sampleRate, name }
        out.write("struct ProgmemKitEntry {\n")
        out.write("  const int16_t* data;\n")
        out.write("  uint32_t       length;\n")
        out.write("  uint32_t       sampleRate;\n")
        out.write("  const char*    name;\n")
        out.write("};\n\n")
        out.write(f"const ProgmemKitEntry PROGMEM_KIT[{len(names)}] = {{\n")
        for n in names:
            out.write(f"  {{ sample_{n}, sample_{n}_len, sample_{n}_rate, \"{n}\" }},\n")
        out.write("};\n")
        out.write(f"const uint8_t PROGMEM_KIT_COUNT = {len(names)};\n\n")
        out.write(f"#endif // {guard}\n")

    total = sum(os.path.getsize(args.output) for _ in [0])
    print(f"Wrote {args.output} ({total} bytes of source)")


if __name__ == "__main__":
    main()
